## Clock
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

## reg[3:0] â†' LEDs
set_property PACKAGE_PIN U16 [get_ports {reg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg[0]}]
set_property PACKAGE_PIN E19 [get_ports {reg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg[1]}]
set_property PACKAGE_PIN U19 [get_ports {reg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg[2]}]
set_property PACKAGE_PIN V19 [get_ports {reg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg[3]}]

## overflow, zero, carry â†' status indicators
set_property PACKAGE_PIN N3 [get_ports {overflow}]
set_property IOSTANDARD LVCMOS33 [get_ports {overflow}]
set_property PACKAGE_PIN P1 [get_ports {zero}]
set_property IOSTANDARD LVCMOS33 [get_ports {zero}]
set_property PACKAGE_PIN L1 [get_ports {carry}]
set_property IOSTANDARD LVCMOS33 [get_ports {carry}]

## 7-Segment Display segments: display[6:0]
set_property PACKAGE_PIN W7 [get_ports {display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]
set_property PACKAGE_PIN W6 [get_ports {display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property PACKAGE_PIN U8 [get_ports {display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property PACKAGE_PIN V8 [get_ports {display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property PACKAGE_PIN U5 [get_ports {display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property PACKAGE_PIN V5 [get_ports {display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property PACKAGE_PIN U7 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
# set_property PACKAGE_PIN V7 [get_ports dp]
# set_property IOSTANDARD LVCMOS33 [get_ports dp]

## Anodes: anode[3:0]
set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
